app = "backend-black-snowflake-3088"
primary_region = "jnb"

[build]
  builder = "heroku/buildpacks:20"         # keep as-is for now (upgrade later)
  buildpacks = ["heroku/nodejs"]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    type = "http"
    interval = "10s"
    timeout = "5s"
    grace_period = "5s"
    method = "GET"
    path = "/healthz"                      # you already serve this
